[PREPROCESSING]
# number of chunks/sub-sections per section
chunks = 4
# minimal size when compared to the average area of top 12 sections
min_size = 0.66
# number of expected sections
n_roi = 12
# how large the overlap btween the chunks is
overlap = 0.05
# pixelsize of the xenium images
pixelsizes = [0.2125,3.0000]
# layers :)
layers = [5,6,7]
# additional space around the roi.
buffer = 0.1 # ten percent

[PATHS]
# enter the path to the xenium output below
data_path = /data/cephfs-2/unmirrored/groups/sawitzki/Juno/data/output-XETG00046__0022430__Region_1__20240704__134614
processed = /data/cephfs-2/unmirrored/groups/sawitzki/Juno/TMA1/processed
# give a name to the sample
sample_name = TMA2
sections_dict = mem_section.json
#  <path to a dictionary with coordinates [[y0,x0],[y1,x1]] for sections of interest>
;home = <>
;bashrc_path = <>

; [METHODS]
;     [DISSECT]
;     img_path = <>
;     gene_mtx_filename = <>
;     platform = xenium
;     config_file = <>
;     weights_file = <>
;     output = <>

;     [CPSAM]


;     [MESMER]
;     membrane = True # False
;     DEEPCELL_ACCESS_TOKEN = 

;     [PROSEG]


;     [STARDIST]


;     [UCS]


;     [CELLVIT]
;     #HE = <>
