# TOML for 10XSegEval
[owner]
name = 'Normann-BPh'


[preprocessing]
# layers user is interested in
planes = [5, 6, 7]
# number of expected sections
n_roi = 12
# additional space around the roi
buffer = 0.01
# number of chunks a section is spli t into for faster processing
# must be 4,9,16,25,...
chunks = 4
# overlap of chunks
overlap = 0.05


[ImageStats]
# stats of the morphology.ome.tif
pixelsize_xy = 0.2125
pixelsize_z = 3.0000


[paths]
# directory the processed data will be saved to; if undefined: uses git-clone location
home = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno'
# directory of Xenium-results
data_path = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno/data/output-XETG00046__0022391__Region_1__20240426__111610'
# give a name to the sample
sample_name = 'TMA3'
# path to ground_truth
ground_truth = '/data/cephfs-1/work/groups/sawitzki/users/juno12_c/segmentation/labels/13-membrane-reordered-overlap_labels.tif'
# path to micromamba or equivalent - relative to home
mm_path = "/work/micromamba/envs"


[methods.cellvit]

[methods.cpsam]
[methods.cpsam.model]
# consult cellpose/models.py#L100 for description of parameters
gpu = true
# available models: cpdino, cpsam_v2, cpdino-vitb, cpsam
pretrained_model = 'cpdino'
# model_type = not used in v4.0.1+
# diam_mean = unknown, not used in v4.0.1+
device = cuda0
use_bfloat16 = true
[methods.cpsam.eval]
# consult cellpose/models.py#L163 for description of parameters
batch_size = 64
resample = true
# channel_axis = morphology has only one channel; ZYX
z_axis = 0
	[methods.cpsam.eval.normalize]
	norm3D = true
# rescale = original size is prefered
# diameter = diameter unknown; original size is prefered
# flow_threshold = 0.4; not used for 3D
cellprob_threshold = 0.0
do_3D = true
flow3D_smooth = 0
# anisotropy = turned off by default
stitch_threshold = 0.0
min_size = 15
max_size_fraction = 0.4
# niter = defaults to None
augment = false
tile_overlap = 0.1
# bsize = defaults to None
# interp = not available for 3D
compute_masks = true
# progress = requires pyqt bar, which opens in external window

[methods.dissect]
platform = 'Xenium'
# config_file = 
# weights_file = 
alpha = 0.5
expand_by = 5
gene = true
#random_seed = No predefined seed
num_proprosal = 1200
isslice = false
# x0 = origin if isslice is true
# y0 = origin if isslice is true
# length = length (x-axis) of slice if isslice is true
# width = width (y-axis) of slice if isslice is true

[methods.mesmer]
token = 'TXYsz750.lLuDd8hLaILIBvFVlOolc5KXs4I36pJv'

[methods.proseg]

[methods.stardist]

[methods.ucs]
# check_gene_map = false


[evaluation]
# if a evaluation should be performed based on
# Jaccard and related scores
JACCARD = false
# Jaccard but by cs-benchmark
CS-BENCH = false
# principal components
PCA = true
# probability density
PD = false
overlay_image = false