# TOML for XenSegEval
[owner]
name = 'Normann-BPh'
mail = 'julius.normann@bih-charite.de'

[Tasks]
preprocess = false
segment = false
evaluate = true

[paths]
# directory the processed data will be saved to
# as default this will be the cloned directory
home = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno'
# directory of Xenium-results
data_path = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno/data/output-XETG00046__0022430__Region_1__20240704__134614'
# give a name to the sample
sample_name = 'TMA2'
# path to ground_truth
gt_path = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno/labels/TMA2_13-3_whole-cell_labels.tif'
# path to the user-defined section
# one must have the same coordinates
# as the gt-masks
sections_path = "mem_section.json"


[ImageStats]
# stats of the morphology.ome.tif
# micrometer per pixel
pixelsize_xy = 0.2125
pixelsize_z = 3.0000
# resolution
y = 64612
x = 51096


[sbatch]
# sbatch job specifications
gpu = "gpu:l40:1"
# time in days
time = 2
# RAM in gigabyte
mem = 64
# nr. cores
cpu = 20


[preprocessing]
# layers user is interested in
# leave list empty if only
# multi-layer required
planes = [5, 6, 7]
# number of expected sections
n_roi = 12
# additional space around the roi
buffer = 0.01
# number of chunks a section is 
# split into for faster processing
# set to zero for None
# must be 0,4,9,16,25,...
chunks = 4
# overlap of chunks in percent
overlap = 0.05


[methods.cpsam.model]
# consult cellpose/models.py#L104 for description of parameters
gpu = true
# available models: cpdino, cpsam_v2, cpdino-vitb, cpsam
pretrained_model = 'cpsam_v2'
# model_type = not used in v4.0.1+
# diam_mean = unknown, not used in v4.0.1+
device = 'cuda:0'
use_bfloat16 = true
[methods.cpsam.eval]
# consult cellpose/models.py#L163 for description of parameters
batch_size = 64
resample = true
# channel_axis = morphology has only one channel; ZYX
z_axis = 0
# rescale = original size is prefered
# diameter = diameter unknown; original size is prefered
# flow_threshold = 0.4; not used for 3D
cellprob_threshold = 0.0
do_3D = true
flow3D_smooth = 0
# anisotropy = turned off by default
stitch_threshold = 0.0
min_size = 15
max_size_fraction = 0.4
# niter = defaults to None
augment = false
tile_overlap = 0.1
# bsize = defaults to None
# interp = not available for 3D
compute_masks = true
# progress = # requires pyqt bar, which opens in external window
[methods.cpsam.eval.normalize]
norm3D = true


[methods.dinocell]


[methods.dissect]
platform = 'xenium'
# config_file = 
# weights_file = 
alpha = 0.5
expand_by = 5
gene = true
#random_seed = No predefined seed
n_jobs = 16
#num_proprosal = # none
#sample_step = #none
#renewal_thres = #none
isslice = false
# x0 = origin if isslice is true
# y0 = origin if isslice is true
# length = length (x-axis) of slice if isslice is true
# width = width (y-axis) of slice if isslice is true
threshold = -0.20
minarea = 600
maxarea = 1200
#fov = none
stride = 128
ratio_stride = 3
neighbor = 8

[methods.mesmer]
token = 'TXYsz750.lLuDd8hLaILIBvFVlOolc5KXs4I36pJv'

[methods.proseg]

[methods.stardist]

#[methods.ucs]
# check_gene_map = false


[evaluation]
# if a evaluation should be performed based on
# Jaccard and related scores
[evaluation.jaccard]
use = false

# Jaccard but by cs-benchmark
[evaluation.cs_bench]
use = false

# not implemented yet
	# principal components
	[evaluation.pca]
	use = false
	
	# probability density
	[evaluation.pd]
	use = false
	overlay_image = false

[evaluation.cross]
use = true
# 'cs' or 'af1'
benchmark = 'af1'
# choose metric according to benchmark
metric = 'Jaccard'
# relevant for 'af1'
threshold = 0.5
