# TOML for 10XSegEval
[owner]
name = 'Normann-BPh'


[preprocessing]
# layers user is interested in
planes = [5, 6, 7]
# number of expected sections
n_roi = 12
# additional space around the roi
buffer = 0.01
# number of chunks a section is split into for faster processing
# must be 4,9,16,...
chunks = 4
# overlap of chunks
overlap = 0.05


[ImageStats]
# stats of the morphology.ome.tif
pixelsize_xy = 0.2125
pixelsize_z = 3.0000


[paths]
# home directory the processed data will be saved to
home = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno'
# directory of Xenium-results
data_path = '/data/cephfs-2/unmirrored/groups/sawitzki/Juno/data/output-XETG00046__0022391__Region_1__20240426__111610'
# give a name to the sample
sample_name = 'TMA3'
# path to .bashrc
bashrc_path = '/data/cephfs-1/home/users/juno12_c/.bashrc'


[methods.cellvit]

[methods.cpsam]

[methods.dissect]
platform = 'Xenium'
# config_file = 
# weights_file = 

[methods.mesmer]

[methods.proseg]

[methods.stardist]

[methods.ucs]
# check_gene_map = false


[evaluation]
# if a evaluation should be performed based on
# F1 and related scores
F1 = true
# principal components
PCA = true
# probability density
PD = true
overlay_image = true