name: segeval
channels:
    - nodefaults
    - conda-forge
    - nvidia
    - pytorch
dependencies:
    - python
    # cpsam
    - qtpy
    - numpy
    - scipy
    #- torch
    #- opencv-python-headless
    - pyqtgraph
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile
    - fastremap
    - cellpose
    - roifile
    - dask
    - distributed
    - dask-image
    - pyyaml
    - zarr
    - dask-jobqueue
    - bokeh
    - fill-voids
    # deepcell
    - scikit-image
    - scikit-learn
    #- tensorflow
    #- tensorflow_addons
    - jupyterlab
    - matplotlib
    - pydot
    # stardist
    - stardist
    - setuptools
    # dissect
    - fvcore
    - joblib
    - numba
    - pandas
    - psutil
    - shapely
    - timm
    - opencv
    - detectron2
    # UCS
    - anndata
    - h5py
    - imgaug
    - rpy2
    - scanpy
    - scvi-tools # might need to switch to scvi(pip) if not backwards comp.
    - pytables
    - umap-learn
    # ana
    - spatialdata
    - aicsimageio
    - tomlkit
    - csbdeep
    - pyarrow
    - cycler
    #
    - pyqt5-sip
    - pip:
        - deepcell
        - deepcell-tracking
        - deepcell-toolbox
        - CellSegmentationEvaluator
        - dissect-st
        - stardist
        - spektral