[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=79"]

[project]
authors = [{name = "Normann-BPh", email = "normann.julius@bih-charite.de"}]
description = "Segment XeniumV2/V3 output using CPSAM, DeepCell, DINOCell, DISSECT, Proseg, Stardist, UCS."
name = "XenSegEval"
requires-python = ">= 3.7"
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT"
license-file = ["LICEN[CS]E*"]
keywords = ["cell segmentation", "transcriptomics"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only"
]
version = "0.1.0"

