[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=80"]

[project]
authors = [{name = "Normann-BPh", email = "normann.julius@bih-charite.de"}]
description = "Segment XeniumV3 output using CPSAM, DeepCell, DINOCell, DISSECT, Proseg, Stardist, UCS."
name = "10xSegEval"
requires-python = ">= 3.7"
readme = "README.md"
#license = 
#license-file
keywords = ["cell segmentation", "transcriptomics"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only"
]
version = "0.1.0"

[project.scripts]
segeval = "10xSegEval:main"
