#!/bin/bash
#
#SBATCH --job-name=boundaries_splitting
#SBATCH --wait#SBATCH --gres=
#SBATCH --time=2-00
#SBATCH --mem=128G
#SBATCH --cpus-per-task=24
#SBATCH --output=/data/cephfs-2/unmirrored/groups/sawitzki/Juno/TMA2/run/processing/boundaries_splitting/logs/%N_%j.out
#SBATCH --error=/data/cephfs-2/unmirrored/groups/sawitzki/Juno/TMA2/run/processing/boundaries_splitting/logs/%N_%j.err
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_90,TIME_LIMIT_80,TIME_LIMIT_50
#SBATCH --mail-user=julius.normann@bih-charite.de
#
. ~/.bashrc
micromamba activate simple
#
python processing/boundaries_splitting.py
