#!/bin/bash
            #
            #SBATCH --job-name=test
            #SBATCH --gres=gpu:l40:1
            #SBATCH --time=2-00
            #SBATCH --mem=64
            #SBATCH --cpus-per-task=6
            #SBATCH --output=/data/cephfs-2/unmirrored/groups/sawitzki/Juno/TMA3/run/bash test.sh/logs/%N_%j.out
            #SBATCH --error=/data/cephfs-2/unmirrored/groups/sawitzki/Juno/TMA3/run/bash test.sh/logs/%N_%j.err
            #SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_90,TIME_LIMIT_80,TIME_LIMIT_50
            #SBATCH --mail-user=julius.normann@bih-charite.de
            #
            bash test.sh